"""init

Revision ID: 54b1d8374afa
Revises:
Create Date: 2025-08-03 20:33:15.155364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54b1d8374afa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "informacoes_gerais", sa.Column("inicio_almoco", sa.Time(), nullable=False)
    )
    op.add_column(
        "informacoes_gerais", sa.Column("fim_almoco", sa.Time(), nullable=False)
    )
    op.add_column(
        "informacoes_gerais", sa.Column("inicio_jantar", sa.Time(), nullable=False)
    )
    op.add_column(
        "informacoes_gerais", sa.Column("fim_jantar", sa.Time(), nullable=False)
    )
    op.drop_column("informacoes_gerais", "periodo_jantar")
    op.drop_column("informacoes_gerais", "periodo_almoco")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "informacoes_gerais",
        sa.Column(
            "periodo_almoco",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "informacoes_gerais",
        sa.Column(
            "periodo_jantar",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("informacoes_gerais", "fim_jantar")
    op.drop_column("informacoes_gerais", "inicio_jantar")
    op.drop_column("informacoes_gerais", "fim_almoco")
    op.drop_column("informacoes_gerais", "inicio_almoco")
    # ### end Alembic commands ###
