"""init

Revision ID: 8cff6910d7dc
Revises: 54b1d8374afa
Create Date: 2025-08-04 19:05:26.246214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cff6910d7dc'
down_revision: Union[str, Sequence[str], None] = '54b1d8374afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.Column('tipo_cliente', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('informacoes_gerais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('preco_almoco', sa.Integer(), nullable=False),
    sa.Column('preco_meia_almoco', sa.Integer(), nullable=False),
    sa.Column('preco_jantar', sa.Integer(), nullable=False),
    sa.Column('preco_meia_jantar', sa.Integer(), nullable=False),
    sa.Column('inicio_almoco', sa.Time(), nullable=False),
    sa.Column('fim_almoco', sa.Time(), nullable=False),
    sa.Column('inicio_jantar', sa.Time(), nullable=False),
    sa.Column('fim_jantar', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('cliente',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('graduando', sa.Boolean(), nullable=False),
    sa.Column('pos_graduando', sa.Boolean(), nullable=False),
    sa.Column('bolsista', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('funcionario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('historico_acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_ator', sa.Integer(), nullable=False),
    sa.Column('usuario_id_alvo', sa.Integer(), nullable=False),
    sa.Column('informacoes_acao', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id_alvo'], ['cliente.usuario_id'], ),
    sa.ForeignKeyConstraint(['usuario_id_ator'], ['funcionario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_acoes')
    op.drop_table('funcionario')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('informacoes_gerais')
    op.drop_table('compra')
    # ### end Alembic commands ###
