name: Test_Runner

on: [push]

jobs:
  run-tests:
    name: python
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Wait for network to be ready
        run: sleep 5

      - name: Network Debugging
        run: |
          echo "--- Pinging db hostname ---"
          ping -c 4 db || echo "Ping to db failed"
          echo "--- Pinging localhost ---"
          ping -c 4 localhost
          echo "--- Checking network ports ---"
          nc -zv localhost 5432
          nc -zv db 5432
          echo "--- Contents of /etc/hosts ---"
          cat /etc/hosts

      - name: Run database migrations
        run: uv run alembic upgrade head
        env:
          DATABASE_URL: "postgresql+psycopg://testuser:testpassword@localhost:5432/testdb"
        
      - name: Run tests
        run: uv run -m unittest
        env:
          DATABASE_URL: "postgresql+psycopg://testuser:testpassword@localhost:5432/testdb"